// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOODZzNLXE0NGl_VufnIfG9gZVAdQO8NY',
    appId: '1:1096168040746:web:1da4e15b8e4c76796a5653',
    messagingSenderId: '1096168040746',
    projectId: 'zudocoz-9451d',
    authDomain: 'zudocoz-9451d.firebaseapp.com',
    storageBucket: 'zudocoz-9451d.appspot.com',
    measurementId: 'G-C5J5GZ75ST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC90rmgiNgy3Z3yS6-FSuenqcQUhEUAPys',
    appId: '1:1096168040746:android:6d579ee2db1cbef86a5653',
    messagingSenderId: '1096168040746',
    projectId: 'zudocoz-9451d',
    storageBucket: 'zudocoz-9451d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDx9QM_8gTSVrN01bdP1OT-aBGryVtYrg',
    appId: '1:1096168040746:ios:b398613893c66ad76a5653',
    messagingSenderId: '1096168040746',
    projectId: 'zudocoz-9451d',
    storageBucket: 'zudocoz-9451d.appspot.com',
    iosBundleId: 'com.example.zudocoz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDx9QM_8gTSVrN01bdP1OT-aBGryVtYrg',
    appId: '1:1096168040746:ios:2d1f5722d52846376a5653',
    messagingSenderId: '1096168040746',
    projectId: 'zudocoz-9451d',
    storageBucket: 'zudocoz-9451d.appspot.com',
    iosBundleId: 'com.example.zudocoz.RunnerTests',
  );
}
